### ISSUE TITLE
'Timer3' was not declared in this scope;

### ISSUE THREAD

**Issue by Waterman178** [Naguissa/uTimerLib#17]
In file included from C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\uTimerLib.cpp:127:
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp: In member function 'void uTimerLib::_attachInterrupt_us(long unsigned int)':
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:52:4: error: 'Timer3' was not declared in this scope; did you mean 'TimerLib'?
   52 |    Timer3->setMode(1, TIMER_OUTPUT_COMPARE);
      |    ^~~~~~
      |    TimerLib
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:56:8: error: '_toInit' was not declared in this scope
   56 |    if (_toInit) {
      |        ^~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:58:43: error: 'interrupt' is not a member of 'uTimerLib'
   58 |     Timer3->attachInterrupt(1, uTimerLib::interrupt);
      |                                           ^~~~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp: In member function 'void uTimerLib::_attachInterrupt_s(long unsigned int)':
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:92:4: error: 'Timer3' was not declared in this scope; did you mean 'TimerLib'?
   92 |    Timer3->setMode(1, TIMER_OUTPUT_COMPARE);
      |    ^~~~~~
      |    TimerLib
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:97:8: error: '_toInit' was not declared in this scope
   97 |    if (_toInit) {
      |        ^~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:99:54: error: 'interrupt' is not a member of 'uTimerLib'
   99 |     Timer3->attachInterrupt((uint32_t) 1, uTimerLib::interrupt);
      |                                                      ^~~~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp: In member function 'void uTimerLib::clearTimer()':
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:139:4: error: 'Timer3' was not declared in this scope; did you mean 'TimerLib'?
  139 |    Timer3->pause();
      |    ^~~~~~
      |    TimerLib
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp: At global scope:
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:174:23: error: no declaration matches 'callback_function_t uTimerLib::interrupt()'
  174 |   callback_function_t uTimerLib::interrupt() {
      |                       ^~~~~~~~~
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\hardware/uTimerLib.STM32.cpp:174:23: note: no functions named 'callback_function_t uTimerLib::interrupt()'
In file included from C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\uTimerLib.cpp:36:
C:\Users\Administrator\Documents\Arduino\libraries\uTimerLib\src\uTimerLib.h:78:8: note: 'class uTimerLib' defined here
   78 |  class uTimerLib {
      |        ^~~~~~~~~
exit status 1

bluepill  stm32f103cbt6    Arduino_Core_STM32  latest version

**Comment by Naguissa** [comment]
Hello,

I will fix it ASAP, meanwhile you can check it here: https://github.com/Naguissa/uTimerLib/issues/16
